Add search module. Add sorting
valeskus/RecipeApp pull request #14
Opened 2023-06-17 15:05 UTC by MAKARD

2023-06-17 15:57 UTC, valeskus requested changes

2023-06-17 15:57 UTC, valeskus commented on receipe-app-api/src/categories/schemas/category.schema.ts
> +        virtuals: true,
what's virtuals?

2023-06-17 15:57 UTC, valeskus commented on receipe-app-api/src/search/search.service.ts
> +                    score: { $meta: "textScore" }
what're we doing here?

2023-06-17 15:57 UTC, valeskus commented on receipe-app-api/src/search/search.service.ts
> +            { $match: { $text: { $search: params.search } } },
what're we doing here?

2023-06-27 14:24 UTC, valeskus requested changes

2023-06-27 14:24 UTC, valeskus commented on receipe-app-api/src/search/search.service.ts
> +            total: totals[0]?.total || 0,
what're you doing here?

2023-06-27 14:24 UTC, valeskus commented on receipe-app-api/src/main.ts
> +  app.useGlobalPipes(new ValidationPipe({
what is the useGlobalPipes?

2023-06-27 14:24 UTC, valeskus commented on receipe-app-api/src/search/aggregations/categories.aggregation.ts
> +interface CategoriesAggregationParams {
what're you doing here?

2023-06-27 14:24 UTC, valeskus commented on receipe-app-api/src/search/aggregations/ranged-facet.aggregation.ts
> +interface RangedFacetAggregationParams<T> {
what's  ranged?

2023-06-27 14:24 UTC, valeskus commented on receipe-app-api/src/search/dto/filters.dto.ts
> +        this.calories = singleFilterTransformation(params.calories, params.inputFilters.calories);
what's the singleFilterTransformation?

2023-06-28 11:12 UTC, MAKARD commented on receipe-app-api/src/search/aggregations/categories.aggregation.ts
> +                { $match: { '_id.type': 'meal' } },
TODO

2023-06-30 11:09 UTC, valeskus approved these changes

2023-06-30 11:09 UTC, merged