F fix recipe details header
valeskus/RecipeApp pull request #4
Opened 2023-06-01 13:36 UTC by valeskus

2023-06-12 17:21 UTC, MAKARD requested changes

2023-06-12 17:21 UTC, MAKARD commented on src/screens/RecipeDetails/components/Header/Header.tsx
> +
remove empty line

2023-06-12 17:21 UTC, MAKARD commented on src/screens/RecipeDetails/components/Header/styles.ts
>      width: '100%',
redundant style, since you've added left:0 and right:0

2023-06-12 17:21 UTC, MAKARD commented on src/screens/RecipeDetails/components/Header/styles.ts
> +    alignContent: 'flex-end',
https://reactnative.dev/docs/flexbox#align-content
"This only has effect when items are wrapped to multiple lines using flexWrap."

2023-06-12 17:21 UTC, MAKARD commented on src/screens/RecipeDetails/components/Header/styles.ts
> +    paddingTop: 40,
does this style make any effect? I'm not sure, 'cause you've already aligned items to the bottom

2023-06-13 09:17 UTC, valeskus commented on src/screens/RecipeDetails/components/Header/styles.ts
> +    paddingTop: 40,
I'm not aligning items to the bottom. I lower them with padding

2023-06-13 10:06 UTC, MAKARD commented on src/screens/RecipeDetails/components/Header/styles.ts
> +    paddingTop: 40,
alignItems: flex-end aligns items to the bottom

2023-06-14 17:27 UTC, MAKARD approved these changes

2023-06-14 17:27 UTC, merged