F fix/style
valeskus/RecipeApp pull request #52
Opened 2023-10-28 13:11 UTC by valeskus

2023-10-28 17:51 UTC, MAKARD submitted a review, later dismissed

2023-11-02 16:22 UTC, MAKARD requested changes

2023-11-02 16:22 UTC, MAKARD commented on src/UI/normalize.ts
> +  } = Dimensions.get('window');
format

2023-11-02 16:22 UTC, MAKARD commented on src/UI/normalize.ts
> +  const scale = SCREEN_WIDTH / 320;
format

2023-11-02 16:22 UTC, MAKARD commented on src/UI/normalize.ts
> +      return Math.round(PixelRatio.roundToNearestPixel(newSize)) - 2;
name that constant according to its purpose

2023-11-02 16:22 UTC, MAKARD commented on src/components/Search/Search.tsx
> +        placeholderTextColor = {Colors.borderTextSecondary}
format

2023-11-04 16:22 UTC, valeskus commented on src/App.tsx
> +      <StatusBar backgroundColor={Colors.background} barStyle={'dark-content'} />
barStyle="..."

2023-11-04 16:22 UTC, valeskus commented on src/UI/normalize.ts
> +export function normalize(size: number) {
write unit tests for this function

2023-11-04 16:22 UTC, valeskus commented on src/screens/RecipeDetails/RecipeDetails.tsx
> +      <StatusBar backgroundColor="transparent" barStyle={'dark-content'}
barStyle="..."

2023-11-04 16:22 UTC, valeskus commented on src/screens/RecipeDetails/components/Header/Header.tsx
> +      <View style={[styles.headerLeftButton, { marginTop: STATUSBAR_HEIGHT }]}>
should be done by https://reactnative.dev/docs/statusbar#currentheight-android

2023-11-04 16:22 UTC, valeskus commented on src/screens/RecipeDetails/components/RecipeDetailsSkeleton/RecipeDetailsSkeleton.tsx
> +const STATUSBAR_HEIGHT = Platform.OS === 'ios' ? normalize(60) : StatusBarManager.HEIGHT + 25;
https://reactnative.dev/docs/statusbar#currentheight-android

2023-11-04 16:22 UTC, valeskus commented on src/screens/RecipeDetails/components/RecipeDetailsSkeleton/RecipeDetailsSkeleton.tsx
> +      <StatusBar backgroundColor="transparent" barStyle={'dark-content'}
barStyle="..."

2023-11-11 14:42 UTC, MAKARD requested changes

2023-11-11 14:42 UTC, MAKARD commented on src/UI/normalize.test.ts
> +    it('should return the same size as we send to normalize the function when the width is 320', () => {
to normalize the function -> to the normalize function

2023-11-11 14:42 UTC, MAKARD commented on src/UI/normalize.test.ts
> +    it('should return a size greater than we send to normalize the function when the width is more than 320', () => {
to normalize the function -> to the normalize function

2023-11-11 14:42 UTC, MAKARD commented on src/screens/RecipeDetails/RecipeDetails.tsx
> +      <StatusBar backgroundColor="transparent" barStyle="dark-content"
format either all props in one line or each prop on a separate line

2023-11-11 14:42 UTC, MAKARD commented on src/screens/RecipeDetails/components/RecipeDetailsSkeleton/RecipeDetailsSkeleton.tsx
> +      <Circle cx={'9.5%'} cy={(StatusBar.currentHeight && StatusBar.currentHeight + 25)} r={normalize(25)} />
what if StatusBar.currentHeight is null/undefined/NaN/false etc

2023-11-11 14:42 UTC, MAKARD commented on src/screens/RecipesList/components/RecipesListMessage/styles.ts
>      width: '100%',
width/height and flex in the same style leads to only flex style active

2023-11-11 18:27 UTC, MAKARD approved these changes, later dismissed

2023-11-12 14:51 UTC, MAKARD approved these changes

2023-11-12 14:51 UTC, merged