F fix/language & nutrients bugs
valeskus/RecipeApp pull request #56
Opened 2023-11-01 15:56 UTC by valeskus

2023-11-02 16:17 UTC, MAKARD requested changes

2023-11-02 16:17 UTC, MAKARD commented on src/managers/LanguageManager/LanguageManager.ts
>        const language = await this.getLanguage();
const language = await this.getLanguage() || 'en';

2023-11-02 16:17 UTC, MAKARD commented on src/screens/RecipeDetails/hooks/useNutrientsController.ts
> +      kCal: (recipe.kCal / recipe.servingsCount) * (numberOfServings || recipe.servingsCount),
should be fixed in another place

2023-11-04 16:01 UTC, valeskus commented on src/screens/RecipeDetails/hooks/useServingsController.ts
> +    if (value === 0 && recipe) {
the fix should not be here

2023-11-11 14:34 UTC, MAKARD requested changes

2023-11-11 14:34 UTC, MAKARD commented on src/UI/Counter/useCounterController.ts
> +      return params.onChange(params.count);
redundant call

2023-11-11 14:34 UTC, MAKARD commented on src/screens/RecipeDetails/hooks/useServingsController.ts
> +  }, [recipe]);
redundant

2023-11-11 18:28 UTC, MAKARD approved these changes

2023-11-11 18:28 UTC, merged