F fix/bugs
valeskus/RecipeApp pull request #60
Opened 2023-11-16 12:17 UTC by valeskus

2023-11-22 17:54 UTC, MAKARD requested changes

2023-11-22 17:54 UTC, MAKARD commented on src/App.tsx
> +      <StatusBar backgroundColor={'transparent'} barStyle="dark-content" translucent={true} />
```
backgroundColor="transparent"
translucent
```

2023-11-22 17:54 UTC, MAKARD commented on src/App.tsx
>  import { NavigationContainer } from '@react-navigation/native';
remove redundant dependency

2023-11-23 08:56 UTC, valeskus commented on src/App.tsx
>  import { NavigationContainer } from '@react-navigation/native';
What is "redundant dependency"?

2023-11-23 10:50 UTC, MAKARD approved these changes

2023-11-23 10:50 UTC, merged